steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip freeze > new-requirements.txt
        cat new-requirements.txt >> requirements.txt  
        sort -u requirements.txt -o requirements.txt  
        cat requirements.txt 


  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy --quiet
timeout: '900s' # Optional: sets the timeout for the build process
options:
  logging: CLOUD_LOGGING_ONLY  # Added this line to fix the service account error